captainVersion: 4
services:
    $$cap_appname:
        image: hectorqin/reader:$$cap_reader_version
        restart: always
        volumes:
            - $$cap_appname-logs:/logs
            - $$cap_appname-data:/storage
        environment: SPRING_PROFILES_ACTIVE=prod
            READER_APP_USERBOOKLIMIT=200
            READER_APP_CACHECHAPTERCONTENT=true
            READER_APP_REMOTEWEBVIEWAPI=http://srv-captain--$$cap_appname-webview:8050
            READER_APP_SECURE=true
            READER_APP_SECUREKEY=$$cap_app_securekey
        caproverExtra:
            containerHttpPort: '8080'
    $$cap_appname-webview:
        image: hectorqin/remote-webview
        container_name: readerwebview
        restart: always
        environment: TZ=Asia/Shanghai
        caproverExtra:
            containerHttpPort: '8050'
caproverOneClickApp:
    variables:
        - id: $$cap_reader_version
          label: Reader Version Tag
          defaultValue: latest
        - id: $$cap_app_securekey
          label: Reader APP Securekey
          defaultValue: admin
    instructions:
        start: YueDu is a tool that offers online literature search, providing a convenient, quick, and comfortable trial reading experience for online literature enthusiasts.
        end: Yuedu is deployed and available as https://$$cap_appname.$$cap_root_domain
    displayName:
    description: YueDu is a tool that offers online literature search, providing a convenient, quick, and comfortable trial reading experience for online literature enthusiasts.
